swagger: "2.0"
info:
  version: 0.0.1
  title: SummerFish Demo
host: localhost:8080
basePath: /
schemes:
- http
- https
paths:
  /ping/:
    get:
      parameters:
      - type: string
        description: ping ID
        name: pingID
        in: query
      operationId: IsAlive
      summary: Is Alive
      tags:
      - ping
      responses:
        "200":
          description: successful operation
  /upload/:
    post:
      parameters:
      - type: file
        description: image
        name: image
        in: formData
      - type: string
        description: params
        name: params
        in: formData
      operationId: UploadImage
      summary: Upload Image
      tags:
      - upload
      responses:
        "200":
          description: successful operation
      consumes:
      - multipart/form-data
