swagger: "2.0"
info:
  version: 0.0.1
  title: SummerFish Demo
host: localhost:8080
basePath: /
schemes:
- http
- https
paths:
  /ping/:
    get:
      parameters:
      - type: string
        description: Ping ID
        name: pingID
        in: query
      operationId: IsAlive_0
      summary: Is Alive
      tags:
      - ping
      responses:
        "200":
          description: successful operation
  /upload/:
    post:
      parameters:
      - type: file
        description: Image
        name: image
        in: formData
      - type: string
        description: Params
        name: params
        in: formData
      operationId: UploadImage_1
      summary: Upload Image
      tags:
      - upload
      responses:
        "200":
          description: successful operation
      consumes:
      - multipart/form-data
